# Database
CREATE DATABASE IF NOT EXISTS nodejs_goals;
USE nodejs_goals;

# Users table
CREATE TABLE IF NOT EXISTS users (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(32) NOT NULL,
    email VARCHAR(64) NOT NULL UNIQUE,
    password CHAR(60) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

# Goals table
CREATE TABLE IF NOT EXISTS goals (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    owner_id INT(11) NOT NULL,
    name VARCHAR(40) NOT NULL,
    end_date TIMESTAMP NOT NULL,
    final_objective DOUBLE(10,2) NOT NULL,
    total DOUBLE(10,2) NOT NULL,
    status TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

# Goal progress table
CREATE TABLE IF NOT EXISTS goals_progress (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    goal_id INT(11) NOT NULL,
    progress_document JSON DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
